const barangays = [
  "Acedillo",
  "Aguit-itan",
  "Alibaba",
  "Anislag",
  "Awang East",
  "Awang West",
  "Bagacay",
  "Bagong Lipunan",
  "Balud",
  "Basud",
  "Bontay ",
  "Buenavista ",
  "Cacaransan",
  "Cagbanayacao",
  "Cagboborac",
  "Cagsalaosao",
  "Cahumpan",
  "Calocnayan",
  "Canhumadac",
  "Capoocan",
  "Carayman",
  "Carmen",
  "Central",
  "Cogon",
  "Dagum ",
  "Dinawacan",
  "Esperanza",
  "Gabay",
  "Gadgaran",
  "Gasdo",
  "Geraga-an",
  "Guimbaoyan Norte",
  "Guimbaoyan Sur",
  "Guin-on",
  "Hamorawon",
  "Helino",
  "Hibabngan",
  "Hibatang",
  "Higasaan",
  "Himalandrog",
  "Jacinto",
  "Jimautan",
  "Kalilihan",
  "Kilikili",
  "La Paz",
  "Langoyon",
  "Lonoy",
  "Looc",
  "Mabini I",
  "Mancol",
  "Matobato",
  "Maybog",
  "Maysalong",
  "Migara",
  "Naga",
  "Naguma",
  "Navarro",
  "Nijaga",
  "Obrero",
  "Olera",
  "Osmeña",
  "Pagbalican",
  "Palanas",
  "Palanogan",
  "Panonongan",
  "Patong",
  "Payahan",
  "Pinamorotan",
  "Rawis",
  "Rizal I and Sitio Caballero",
  "Roxas I",
  "Salvacion",
  "San Antonio",
  "San Isidro",
  "San Jose",
  "San Policarpio",
  "Saputan",
  "Sinantan",
  "Tabawan",
  "Tanval",
  "Tapa-e",
  "Tigbe",
  "Trinidad",
  "Victory",
  "Villahermosa",
];
export const allBarangay = { barangays: barangays };
