import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import { setCookie } from "cookies-next";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from TRPC" });

  setCookie("key", "value");

  return (
    <>
      <Head>
        {/* <title>Ping Ping's Tinapa</title> */}
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-between bg-gradient-to-l from-[#c9f2ff] to-[#3b98b4] p-10">
        <div className=" h-20 w-full"></div>
        <div className="  flex w-full flex-row">
          <div className=" w-1/2">
            <span className="z-10 -mt-36 flex flex-col font-cavean text-10xl font-black text-white drop-shadow-lg  sm:flex-row sm:text-10xl ">
              <span className=" -mt-44  text-[#fffaed] sm:mt-0">Ping</span>
              <span className=" hidden sm:flex">-</span>
              <span className=" -mt-44 text-[#ffc233] sm:mt-0">Ping's</span>
            </span>
            <div className=" -mt-14 w-full  p-2 sm:p-5 lg:-mt-16">
              <span className=" font-cavean text-4xl text-[#ffffff] sm:text-6xl">
                Smoked Fish ( <span>Tinapa</span> )
              </span>
            </div>
            <div className="ml-10 mt-10 flex w-full flex-col gap-2 sm:flex-row sm:gap-0">
              <button className="z-0 mr-0 rounded-xl bg-[#023047] p-5 pr-10 font-rubik text-3xl font-medium text-[#ffffff] shadow-md transition hover:-translate-x-2 hover:bg-[#09223a] hover:shadow-xl sm:-mr-8 sm:pr-12">
                Our Products
              </button>
              <button className=" z-10 rounded-xl bg-[#ffc233] p-5 px-10 font-rubik text-3xl font-medium text-[#023047] shadow-md transition hover:scale-105 hover:bg-[#ffbb1e] hover:shadow-xl">
                Order Now!
              </button>
            </div>
          </div>
          <div className=" w-1/2"></div>
        </div>
        <div className=" h-20 w-full"></div>
      </main>
    </>
  );
}
